import { defaultTheme } from '@pawi/theme'

export const styledTheme = {
  badgeTop: '-0.8rem',
  badgeRight: '-0.8rem',
  badgeHeight: '1.1rem',
  badgeWidth: '1.15rem',
  badgeBorder: '1px solid white',
  badgeBorderRadius: '1rem',
  badgeBackground: '#ff6900b8',
  badgeLineHeight: '1.2rem',
  badgeColor: 'white',
  badgeFontSize: '0.8rem',
  buttonActiveBackground: '#bbb',
  buttonBackground: '#ccc',
  buttonHoverBackground: '#ddd',
  buttonBorderRadius: '5px',
  buttonColor: '#222',
  buttonPrimaryActiveBackground: '#506598',
  buttonPrimaryColor: '#fff',
  buttonPrimaryBackground: '#506598',
  buttonPrimaryHoverBackground: '#7287ba',
  buttonMargin: '1rem',
  buttonLargeWidth: '12rem',
  buttonLargePadding: '0.5rem 0.9rem',
  buttonWidth: '7rem',
  buttonPadding: '0.5rem 0.6rem',
  cardBackground: '#eee',
  cardBorder: '1px solid #5f6471',
  cardBorderRadius: '5px',
  cardBoxShadow: '4px 14px 50px rgba(0, 0, 0, 0.3)',
  cardColor: '#333',
  // Used by other libs to set color of separators in
  // card parts.
  cardItemBorder: '1px solid #808080',
  cardLargeWidth: '36rem',
  cardMediumWidth: '24rem',
  cardTitleBackground: '#506598',
  cardTitleErrorBackground: '#986550',
  cardTitleColor: '#fff',
  cardWidth: '18rem',
  errorMessageBackground: '#f9d7d7',
  errorMessageBorder: '1px solid #c39a9a',
  errorMessageColor: '#dc6565',
  errorMessagePadding: '1rem',
  errorMessageBorderRadius: '5px',
  fieldCheckedBackground: '#f3d3ec',
  fieldIconBackground: '#ccc',
  fieldIconPadding: '0 0.5rem',
  fieldInfoColor: '#777',
  fieldInfoBackground: 'none',
  fieldInfoBorder: '1px solid #ddd',
  fieldInfoInputColor: '#555',
  fieldInfoInputFontWeight: 'bold',
  fieldBorder: '1px solid #ccc',
  // This should be a singl value.
  fieldMargin: '1rem',
  fieldBorderRadius: '2px',
  iconDisabledOpacity: '0.4',
  iconLargeFontSize: '1.6rem',
  iconMediumFontSize: '1.3rem',
  iconMargin: '0.4em',
  inputColor: '#333',
  inputResetColor: '#d2d8e2',
  inputResetColorHover: '#94a1c1',
  inputBorderRadius: '5px',
  inputBackground: '#eee',
  inputFontSize: '1rem',
  inputLineHeight: '1.6rem',
  inputPadding: '0.2rem 0.5rem 0 0.5rem',
  inputPlaceholderColor: '#a5a5a5',
  inspectorBackground: '#484545',
  // Must be in px because it is parsed for minWidth of Resizable
  inspectorWidth: '400px',
  inspectorIconHighColor: '#3c92e0',
  inspectorTitlePadding: '0.5rem',
  inspectorTitleHeight: '1.8rem',
  inspectorTitleFontSize: '1.2rem',
  inspectorTitleBackground: '#4c596b',
  inspectorTitleColor: '#9aa5b7',
  inspectorTitleBorderBottom: '1px solid #2d3b48',
  inspectorWidgetBackground: '#b6cae6',
  inspectorWidgetBorderLeft: '1px solid #79879a',
  messageMargin: '2rem 1rem',
  modalBackground: 'rgba(144, 144, 144, 0.83)',
  modalBackdropFilter: 'blur(1.5px)',
  modalTopMargin: '10vh',
  // Height to width ratio
  pageRatio: 297 / 210,
  // This width, pageHeader and pageFooter MUST be expressed in pixels because
  // the values are used to compute available page height for content (in px).
  pageBackground: '#fbfbfb',
  pageBoxShadow: '0 0.5mm 2mm rgba(0, 0, 0, 0.3)',
  // Must be in px as it is parsed
  pageWidth: '1024px',
  pageFooterHeight: '100px',
  pageHeaderHeight: '100px',
  // Must be in px as it is parsed
  pageMarginLeftRight: '64px',
  pageMarginTopBottom: '64px',
  pageOuterMargin: '41px 0',
  roundInputLightBackground: '#ececec',
  roundInputBackground: '#ddd',
  roundInputBorderRadius: '1rem',
  roundInputPadding: '0.2rem 0.5rem 0.2rem 0.8rem',
  roundInputResetTop: '0.5rem',
  roundInputResetRight: '0.5rem',
  roundInputResetColor: '#bbb',
  separatorBorder: '1px solid #bbb',
  separatorBorderWidth: '1px 0 0 0',
  optionPadding: '3px 10px',
  optionColor: 'inherit',
  optionBackground: 'var(--cardBackground)',
  optionHoverColor: '#333',
  optionHoverBackground: '#ffd588',
  optionSelectedColor: 'inherit',
  optionSelectedBackground: '#ffd588',
  optionPreviousSelectedBackground: '#ecdab7',
  resizeHandleBackground: '#adbccadb',
  resizeHandleBorder: 'none',
  scrollTrackBorder: 'none',
  scrollTrackBg: 'transparent',
  scrollBarWidth: '8px',
  scrollBarLargeWidth: '10px',
  scrollBarBg: 'transparent',
  scrollThumbBg: '#ccc',
  scrollBarRadius: '10px',
  selectMargin: '0.8rem 0',
  tableBackground: '#e6e6e6',
  tableHeaderColor: 'var(--tableRowColor)',
  tableHeaderBackground: '#b3bcd6',
  tableRowColor: '#444',
  tableRowBackgroundEven: 'var(--tableBackground)',
  tableRowBackgroundOdd: '#e0e0e0',
  tableRowBorder: 'none',
  tableRowHeight: '1em',
  tableRowPaddingV: '0.5em',
  tableRowPaddingH: '0.25em',
  tableRowHoverBackground: '#afafaf',
  tableRowIdent: '29px',
  titleTextMargin: '0.5rem 0.6rem 0.3rem',
}

export const styledDefaultTheme = Object.assign({}, defaultTheme, styledTheme)
